### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by xiong-zx** [jskherman/jsk-lecnotes#1]
Hi, your template is amazing and I want to use it. However, I encountered the following error when compiling (using the Typst Web App):

> Within @preview/codelst:1.0.0 this problem occured:
> content does not contain field "counter"

I have no idea why this happens.

**Comment by jskherman** [comment]
Hi sorry for taking a while, simply just update the version of the `codelst` package imported in `template.typ` to `2.0.1` which is the latest currently in [Typst Universe](https://typst.app/universe/package/codelst).

https://github.com/jskherman/jsk-lecnotes/blob/d7583d3b386476a383df22deebe7fb0ced81f359/template.typ#L4

```diff
- #import "@preview/codelst:1.0.0": sourcecode, codelst
+ #import "@preview/codelst:2.0.1": sourcecode, codelst
```

**Comment by xiong-zx** [comment]
Thanks. This works. Your template is amazing!

**Comment by xiong-zx** [comment]
Thanks. This works. Your template is amazing!
